name: Demo workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  resourceUtilization:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: resource utilization
        run: bash resourceUtilization.sh
        shell: bash
